#homeassistant:
#  name: Home
#  latitude: !secret latitude
#  longitude: !secret longitude
#  elevation: !secret elevation
#  unit_system: imperial
#  time_zone: America/New_York

alarm_control_panel: !include include/alarm_control_panel.yaml
ambient_station: !include include/ambientstation.yaml
arlo: !include include/arlo.yaml
automation: !include automations.yaml
camera: !include include/camera.yaml
config:
device_tracker: !include include/device_tracker.yaml
discovery:
  ignore:
    - songpal
frontend: !include include/frontend.yaml
google_assistant: !include include/google_assistant.yaml
group: !include_dir_merge_named include/groups
history: !include include/history.yaml
http: !include include/httpconfig.yaml
hue: !include include/hue.yaml
influxdb: !include include/influxdb.yaml
input_boolean: !include include/inputboolean.yaml
logbook:
logger: !include include/logger.yaml
map:
mobile_app:
notify: !include include/notify.yaml
recorder: !include include/recorder.yaml
scene: !include_dir_merge_list include/scenes
sense: !include include/sense.yaml
sensor: !include_dir_merge_list include/sensors
speedtestdotnet: !include include/speedtest.yaml
sun:
system_health:
updater:
wink:
weather: !include include/weather.yaml
zwave: !include include/zwave.yaml
