homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  time_zone: America/New_York
  customize: !include_dir_merge_named customize

#usps: !include include/usps.yaml
#wake_on_lan:
alarm_control_panel: !include include/alarm_control_panel.yaml
#arlo: !include include/arlo.yaml
automation: !include automations.yaml
camera: !include include/camera.yaml
config:
device_tracker: !include include/device_tracker.yaml
discovery:
  ignore:
    - songpal
emulated_hue: !include include/emulated_hue.yaml
frontend:
group: !include_dir_merge_named include/groups
history: !include include/history.yaml
http: !include include/httpconfig.yaml
influxdb: !include include/influxdb.yaml
input_boolean: !include include/inputboolean.yaml
logbook:
logger: !include include/logger.yaml
media_player: !include include/media_player.yaml
notify: !include include/notify.yaml
recorder: !include include/recorder.yaml
scene: !include_dir_merge_list include/scenes
sensor: !include_dir_merge_list include/sensors
sun:
updater:
wink:
zwave: !include include/zwave.yaml
hue: !include include/hue.yaml
google_assistant: !include include/google_assistant.yaml
